name       : perl-pdf-api2
version    : 2.033
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/S/SS/SSIMMS/PDF-API2-2.033.tar.gz : 9c0866ec1a3053f73afaca5f5cdbe6925903b4ce606f4bf4ac317731a69d27a0
license    : LGPL-2.1
component  : programming.perl
summary    : Facilitates the creation and modification of PDF files
description: |
    Facilitates the creation and modification of PDF files.
builddeps  :
    - perl-devel-cycle
    - perl-font-ttf
    - perl-sub-uplevel
    - perl-test-exception
    - perl-test-memory-cycle
rundeps    :
    - perl-font-ttf
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
