name       : perl-pdf-api2
version    : '2.044'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/S/SS/SSIMMS/PDF-API2-2.044.tar.gz : b2d15579e42723d8d7f9b72de86d0d35cde34f1eb7713456ba2ad35fb3cbea7e
homepage   : https://metacpan.org/pod/PDF::API2
license    : LGPL-2.1-or-later
component  : programming.perl
summary    : PDF::API2 - Create, modify, and examine PDF files
description: |
    Facilitates the creation and modification of PDF files.
builddeps  :
    - perl-devel-cycle
    - perl-font-ttf
    - perl-sub-uplevel
    - perl-test-exception
    - perl-test-memory-cycle
rundeps    :
    - perl-font-ttf
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
