name       : perl-pdf-api2
version    : '2.043'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/S/SS/SSIMMS/PDF-API2-2.043.tar.gz : 6312f605172973fa4d017639c217b61b1a8d6c533237ce58d5aacecfa273f0b2
homepage   : https://metacpan.org/pod/PDF::API2
license    : LGPL-2.1-or-later
component  : programming.perl
summary    : PDF::API2 - Create, modify, and examine PDF files
description: |
    Facilitates the creation and modification of PDF files.
builddeps  :
    - perl-devel-cycle
    - perl-font-ttf
    - perl-sub-uplevel
    - perl-test-exception
    - perl-test-memory-cycle
rundeps    :
    - perl-font-ttf
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
