name       : perl-pdf-api2
version    : '2.039'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/S/SS/SSIMMS/PDF-API2-2.039.tar.gz : 36a74318847fe92ecec45221bc78f209e194f9f979521710a89ef7baa955a123
license    : LGPL-2.1
component  : programming.perl
summary    : Facilitates the creation and modification of PDF files
description: |
    Facilitates the creation and modification of PDF files.
builddeps  :
    - perl-devel-cycle
    - perl-font-ttf
    - perl-sub-uplevel
    - perl-test-exception
    - perl-test-memory-cycle
rundeps    :
    - perl-font-ttf
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
